language: python
python:
 - "2.6"
 - "2.7"
# Someday, soon.
# - "3.3"
install: python setup.py install
script: python setup.py test
notifications:
    email: moschlar@metalabs.de
#    irc:
#        - "irc.freenode.net#toscawidgets"
    on_success: change
    on_failure: always
